server:
  port: 8080

spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: 106.15.170.117  #用linux的ip地址（consul在本机就填localhost）
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
